### ISSUE TITLE
Pathways in DAG, but missing from ReactomePathways.txt

### ISSUE THREAD

**Issue by dvklopfenstein** [reactome/graph-core#2]
Thank you very much for your the Reactome Knowledgebase and the tools to access it. The DAG is a great way to go. Before using the DAG, I used the content service.

I am finding a minor mismatch in the data (Reactome version 67) between the pathway list from the Content Service and from the DAG:

These two Pathways are seen in the DAG, but not seen in  **ReactomePathways.txt** from the content service. These pathways are in other files from the content service, but not **ReactomePathways.txt**

```
MATCH (p:Pathway) WHERE p.stId IN ['R-RNO-215126', 'R-SCE-2564818'] RETURN p.stId as ID, p.displayName AS Name

ID | Name
-- | --
"R-RNO-215126" | "Transport of connexins along the secretory pathway"
"R-SCE-2564818" | "Cytosolic iron-sulfur cluster assembly (yeast)"
```

Grepping for these two pathways in **ReactomePathways.txt**  come back with no results:
```
$ grep R-SCE-2564818 ReactomePathways.txt

$ grep R-RNO-215126 ReactomePathways.txt
```

PS: Is this the correct repo for this issue?

Thank you again for Reactome. We are so fortunate to have such a great resource.

**Comment by fabregat** [comment]
Hi there,

The reason why these two pathways are not included in the file is because they are orphan pathways, meaning that they cannot be reached from any TopLevelPathway of their respective species (following the "hasEvent" relationship).

A similar report was recently received in our help desk (help@reactome.org) and the issue will be investigated by our curators and release pipeline staff.

Thank you very much for your interest in using Reactome data and software.

Best regards,
